sudo: required
services:
    - docker

before_install:
    - docker build -t yurashni/react-tests -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true yurashni/react-tests npm test

after_success:
    - docker build -t yurashni/multi-client ./client
    - docker build -t yurashni/multi-nginx ./nginx
    - docker build -t yurashni/multi-server ./server
    - docker build -t yurashni/multi-worker ./worker

    - echo '$DOCKER_PASS' | docker login -u '$DOCKER_ID' --password-stdin

    - docker push yurashni/multi-client
    - docker push yurashni/multi-nginx
    - docker push yurashni/multi-server
    - docker push yurashni/multi-worker